-- MySQL Script generated by MySQL Workbench
-- Tue May 23 15:33:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autovrumvrum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autovrumvrum
-- -----------------------------------------------------
DROP SCHEMA `autovrumvrum`;
CREATE SCHEMA IF NOT EXISTS `autovrumvrum` DEFAULT CHARACTER SET utf8mb4 ;
USE `autovrumvrum` ;

-- -----------------------------------------------------
-- Table `autovrumvrum`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Fornecedor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(75) NOT NULL,
  `Tipo` ENUM('Individual', 'Empresa') NOT NULL,
  `NIF` INT NOT NULL,
  CONSTRAINT chk_nif_forn CHECK(LENGTH(nif)=9), 
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Funcionario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(75) NOT NULL,
  `Genero` VARCHAR(1) NOT NULL,
  CONSTRAINT `chk_Genero_fun` CHECK(Genero = 'F' OR Genero = 'M' OR Genero = 'I'),
  `Data_de_Nascimento` DATE NOT NULL,
  `NIF` INT NOT NULL,
  CONSTRAINT `chk_nif_fun` CHECK(LENGTH(nif)=9), 
  `Tipo` ENUM('Vendedor', 'Comprador') NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Cliente` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(75) NOT NULL,
  `Genero` VARCHAR(1) NOT NULL,
  CONSTRAINT `chk_Genero_cli` CHECK(Genero = 'F' OR Genero = 'M' OR Genero = 'I'),
  `Data_de_Nascimento` DATE NOT NULL,
  `NIF` INT NOT NULL,
  CONSTRAINT `chk_nif_cli` CHECK(LENGTH(nif)=9), 
  `Morada` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Compra` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Data_Compra` DATE NOT NULL,
  `Preco` DOUBLE NOT NULL,
  CONSTRAINT `chk_preco_compra` CHECK(`preco` >= 0.0),
  `Funcionario_ID` INT NOT NULL,
  `Fornecedor_ID` INT NOT NULL,
  `Carro_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Compra_Funcionario1_idx` (`Funcionario_ID` ASC) VISIBLE,
  INDEX `fk_Compra_Fornecedor1_idx` (`Fornecedor_ID` ASC) VISIBLE,
  INDEX `fk_Compra_Carro1_idx` (`Carro_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Funcionario1`
    FOREIGN KEY (`Funcionario_ID`)
    REFERENCES `autovrumvrum`.`Funcionario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Fornecedor1`
    FOREIGN KEY (`Fornecedor_ID`)
    REFERENCES `autovrumvrum`.`Fornecedor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Carro1`
    FOREIGN KEY (`Carro_ID`)
    REFERENCES `autovrumvrum`.`Carro` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Venda` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Data_Venda` DATE NOT NULL,
  `Preco` DOUBLE NOT NULL, 
  CONSTRAINT `chk_preco_venda` CHECK(`preco` >= 0.0),
  `Cliente_ID` INT NOT NULL,
  `Funcionario_ID` INT NOT NULL,
  `Carro_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_ID` ASC) VISIBLE,
  INDEX `fk_Venda_Funcionario1_idx` (`Funcionario_ID` ASC) VISIBLE,
  INDEX `fk_Venda_Carro1_idx` (`Carro_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `autovrumvrum`.`Cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`Funcionario_ID`)
    REFERENCES `autovrumvrum`.`Funcionario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Carro1`
    FOREIGN KEY (`Carro_ID`)
    REFERENCES `autovrumvrum`.`Carro` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `autovrumvrum`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Carro` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(50) NOT NULL,
  `Modelo` VARCHAR(75) NOT NULL,
  `Ano` INT NOT NULL,
  `Kilometros` INT NOT NULL,
  CONSTRAINT `chk_kilometros` CHECK(`kilometros` >= 0),
  `Cilindrada` INT NOT NULL,
  CONSTRAINT `chk_cilindrada` CHECK(`cilindrada` >= 0),
  `Combustivel` ENUM('Gasolina', 'Gasoleo', 'Hibrido', 'Eletrico', 'Gas') NOT NULL,
  `Preco` DOUBLE NOT NULL,
  CONSTRAINT `chk_preco_carro` CHECK(`preco` >= 0.0),
  `Estado` VARCHAR(75) NOT NULL,
  `Fornecedor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Carro_Fornecedor1_idx` (`Fornecedor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Carro_Fornecedor1`
    FOREIGN KEY (`Fornecedor_ID`)
    REFERENCES `autovrumvrum`.`Fornecedor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`TestDrive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`TestDrive` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Data_Ocorrencia` DATE NOT NULL,
  `Cliente_ID` INT NOT NULL,
  `Funcionario_ID` INT NOT NULL,
  `Carro_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Carro_ID`),
  INDEX `fk_Test Drive_Cliente1_idx` (`Cliente_ID` ASC) VISIBLE,
  INDEX `fk_Test Drive_Funcionario1_idx` (`Funcionario_ID` ASC) VISIBLE,
  INDEX `fk_Test Drive_Carro1_idx` (`Carro_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Test Drive_Cliente1`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `autovrumvrum`.`Cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test Drive_Funcionario1`
    FOREIGN KEY (`Funcionario_ID`)
    REFERENCES `autovrumvrum`.`Funcionario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test Drive_Carro1`
    FOREIGN KEY (`Carro_ID`)
    REFERENCES `autovrumvrum`.`Carro` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Telemovel_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Telemovel_Cliente` (
  `Telemovel` INT NOT NULL,
  CONSTRAINT `chk_telemovel_cli` CHECK(LENGTH(Telemovel)=9),
  `Cliente_ID` INT NOT NULL,
  PRIMARY KEY (`Telemovel`, `Cliente_ID`),
  INDEX `fk_Telemovel_Cliente_Cliente1_idx` (`Cliente_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Telemovel_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `autovrumvrum`.`Cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Email_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Email_Cliente` (
  `Email` VARCHAR(90) NOT NULL,
  `Cliente_ID` INT NOT NULL,
  PRIMARY KEY (`Email`, `Cliente_ID`),
  INDEX `fk_Email_Cliente_Cliente1_idx` (`Cliente_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Email_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `autovrumvrum`.`Cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Email_Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Email_Fornecedor` (
  `Email` VARCHAR(90) NOT NULL,
  `Fornecedor_ID` INT NOT NULL,
  PRIMARY KEY (`Email`, `Fornecedor_ID`),
  INDEX `fk_Email_Fornecedor_Fornecedor1_idx` (`Fornecedor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Email_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_ID`)
    REFERENCES `autovrumvrum`.`Fornecedor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Telemovel_Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Telemovel_Fornecedor` (
  `Telemovel` INT NOT NULL,
  CONSTRAINT `chk_telemovel_forn` CHECK(LENGTH(Telemovel)=9),
  `Fornecedor_ID` INT NOT NULL,
  PRIMARY KEY (`Telemovel`, `Fornecedor_ID`),
  INDEX `fk_Telemovel_Fornecedor_Fornecedor1_idx` (`Fornecedor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Telemovel_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_ID`)
    REFERENCES `autovrumvrum`.`Fornecedor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Email_Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Email_Funcionario` (
  `Email` VARCHAR(90) NOT NULL,
  `Funcionario_ID` INT NOT NULL,
  PRIMARY KEY (`Email`, `Funcionario_ID`),
  INDEX `fk_Email_Funcionario_Funcionario1_idx` (`Funcionario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Email_Funcionario_Funcionario1`
    FOREIGN KEY (`Funcionario_ID`)
    REFERENCES `autovrumvrum`.`Funcionario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autovrumvrum`.`Telemovel_Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autovrumvrum`.`Telemovel_Funcionario` (
  `Telemovel` INT NOT NULL,
  CONSTRAINT `chk_telemovel_func` CHECK(LENGTH(Telemovel)=9),
  `Funcionario_ID` INT NOT NULL,
  PRIMARY KEY (`Telemovel`, `Funcionario_ID`),
  INDEX `fk_Telemovel_Funcionario_Funcionario1_idx` (`Funcionario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Telemovel_Funcionario_Funcionario1`
    FOREIGN KEY (`Funcionario_ID`)
    REFERENCES `autovrumvrum`.`Funcionario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
